services:
  postgres:
    container_name: postgres_docker
    build:
      context: .
      dockerfile: setup-postgres/Dockerfile.postgres
    environment:
      LOCAL_USER: ${LOCAL_USER}
      LOCAL_PASSWORD: ${LOCAL_PASSWORD}
      LOCAL_DB: ${LOCAL_DB}
      POSTGRES_PASSWORD: ${LOCAL_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      REMOTE_HOST: ${REMOTE_HOST}
      REMOTE_PORT: ${REMOTE_PORT}
      REMOTE_USER: ${REMOTE_USER}
      REMOTE_PASSWORD: ${REMOTE_PASSWORD}
      REMOTE_DB: ${REMOTE_DB}
    networks:
      - postgres_network
    ports:
      - "${LOCAL_PORT}:5432"

  pgadmin:
    container_name: pgadmin_docker
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8888:80"
    depends_on:
      - postgres
    links:
      - postgres

  back:
    build:
      context: .
      dockerfile: setup-back/Dockerfile.back
    container_name: php_docker
    restart: always
    volumes:
      - ./setup-back/back:/var/www/projeto
    ports:
      - "80:80"
    depends_on:
      - postgres

  front:
    build:
      context: .
      dockerfile: setup-front/Dockerfile.front
    container_name: front_docker
    restart: always
    volumes:
      - ./setup-front/front:/var/www/html
    ports:
      - "8080:80"

volumes:
  pg_data:

networks:
  postgres_network:
    driver: bridge